# Generated by Django 5.2.6 on 2025-11-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='attendees',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
