# Generated by Django 5.2.6 on 2025-11-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
